AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  battlesnake-web-lambda

  Sample SAM Template for battlesnake-web-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1
    Environment:
      Variables:
        LIBHONEY_DATASET: !Ref HoneycombDataset
        LIBHONEY_API_KEY: !Ref HoneycombApiKey
        RUST_LOG: info

Parameters:
  HoneycombApiKey:
    Type: String
    Description: API Key for Honeycomb
  HoneycombDataset:
    Type: String
    Description: Honeycomb Dataset to send to
    Default: battlesnake-stats


Resources:
  Devin:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "../target/lambda/web-lambda.zip"
      Handler: N/A
      Runtime: provided
      MemorySize: 1024
      Timeout: 10
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 5
      Events:
        WebApiEvent:
          Type: HttpApi
          Properties:
            Path: '/devious-devin/{path+}'
            Method: Any
  Hobbs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "../target/lambda/web-lambda.zip"
      Handler: N/A
      Runtime: provided
      MemorySize: 1024
      Timeout: 10
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 5
      Events:
        WebApiEvent:
          Type: HttpApi
          Properties:
            Path: '/hovering-hobbs/{path+}'
            Method: Any
  BattlesnakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "../target/lambda/web-lambda.zip"
      Handler: N/A
      Runtime: provided
      MemorySize: 256
      Timeout: 1
      Events:
        WebApiEvent:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BattlesnakeFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BattlesnakeFunctionRole.Arn
