# fly.toml file generated for battlesnake-rs on 2022-01-21T21:36:16-05:00

app = "battlesnake-rs"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FORCE_DEPLOY_BY_CHANGING_THIS_VARIABLE = "2"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 4
    soft_limit = 1
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
