[package]
name = "sherlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.82"
ureq = { version = "2.4.0", features = ["json"] }
clap = { version = "3.2.8", features = ["derive"] }

types = { path = "../types" }

battlesnake-minimax = { path = "../battlesnake-minimax" }
itertools = "0.10.3"
dashmap = "5.3.4"
