name: Rust Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: v0
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - name: Build | Lint
        run: cargo clippy --all-targets --no-deps --locked
  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: v0
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - name: Cargo Doc
        run: cargo doc --workspace --no-deps --locked
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: v0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - name: Test
        run: cargo test --locked
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: v0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - name: Bench
        run: cargo bench --locked
      - name: Archive Bench Statistics
        uses: actions/upload-artifact@v3
        with:
          name: criterion-bench
          path: target/criterion
  profile:
    name: Profile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: v0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - name: Profile Hobbs
        run: cargo bench --bench hobbs -- --profile-time 60
      - name: Profile Irene
        run: cargo bench --bench improbable_irene -- --profile-time 60
      - name: Archive Profile Statistics
        uses: actions/upload-artifact@v3
        with:
          name: criterion-bench
          path: target/criterion
